version: 1.0.{build}
image: Ubuntu2004
environment:
  nodejs_version: "18"
  GITHUB_TOKEN:
    secure: 2YjVzBsSXLSSFG4rX5qAPqRr2vbfr1EcYFeIwAdV6hZyCVFcoV2PNG3R/BbdeJf7

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

build_script:
  - yarn build

deploy:
  provider: script
  script: yarn deploy
  on:
    branch: main

on_success:
  - git config --global user.email "appveyor@example.com"
  - git config --global user.name "Appveyor CI"
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/fedoweb/whack-and-goblin-yarn.git
  - npx gh-pages -d dist -r https://$GITHUB_TOKEN@github.com/fedoweb/whack-and-goblin-yarn.git